Todos App feature
biruk-bereka/react-todos-application pull request #1
Opened 2023-02-21 19:12 UTC by biruk-bereka

## In this PR I:
 - Set up project using vite
 - Use Components to build the website
 - Use localstorage to store todos data on browser
- Use react icons for the website
- Use react router for routing the page

2023-02-21 20:06 UTC, kensteph requested changes
# Required Changes ♻️

Hi  @biruk-bereka

You did a great job so far! Congratulations! 🎉
## To Highlight 

-  Highly organized code. ✔️
-  No linter errors. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

## Improvements
Please consider:
   - Improve the design
   
![image](https://user-images.githubusercontent.com/39686386/220445896-aa191c1f-8679-4a4a-8c33-edf6dd543455.png)

Cheers and Happy coding 👏🏽👏🏽

2023-02-21 20:06 UTC, kensteph commented on src/components/Navbar.jsx
> +        </li>
Please consider working on the navbar to improve the design.

![image](https://user-images.githubusercontent.com/39686386/220443061-77d6d5e8-ee36-4c7d-ab85-2ca1704472a8.png)

2023-02-21 20:06 UTC, kensteph commented on src/components/TodoItem.jsx
> +  };
I think here you could toggle the input for the user. When the user clicks on the edit icon if he is already in editing mode, the user can leave the mode by hiding the input. So instead of using `setEditing(true)` you can use `setEditing(!editing)` to toggle the input.

2023-02-22 05:46 UTC, biruk-bereka commented on src/components/Navbar.jsx
> +        </li>
Thank you for you feedback.

2023-02-22 05:49 UTC, biruk-bereka commented on src/components/TodoItem.jsx
> +  };
Thank you for the feedback.

2023-02-22 13:19 UTC, kensteph approved these changes
# Status Approved ✅

Hi @biruk-bereka

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉
## To Highlight 
✅Functionalities work as expected
✅Highly organized code.
✅No linter errors.
✅Professional README file.
✅PR has a good title and summary. 

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding 👏🏽👏🏽

2023-02-22 14:00 UTC, merged